export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_FOOD_CATEGORIES = 'receive_food_categories'
export const RECEIVE_SHOPS = 'receive_shops'
export const SAVE_USER = 'save_user'
export const SAVE_TOKEN = 'save_token'